pipeline {
    agent {
        label 'agent1'
    }
    parameters {
        choice(name: 'GitBranch', choices: ['main', 'dev', 'test'], description: 'please select your Branch')

        string(name: 'ImageName', defaultValue: 'jenkinsapp', description: 'Enter Image Name')

        string(name: 'ContainerName', defaultValue: 'test-main-app', description: 'Enter Container Name')
        
        string(name: 'ContainerPort', defaultValue: '5000', description: 'Enter Container Expose Port')

    }
    stages {
        stage('scm checkout') {
            steps {
              git url:"https://github.com/mishti30/jenkins-docker-project.git", branch: "${params.GitBranch}"
            }
        }

        stage('create Image') {
            steps {
                sh "docker build -t ${params.ImageName}:latest ."
            }
        }

        stage('Image push to Repo '){
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-repo-creds', usernameVariable: 'docker_user', passwordVariable: 'docker_pass')]) {
                sh "docker tag ${params.ImageName} ${env.docker_user}/${params.ImageName}:latest"
                sh "docker login -u ${env.docker_user} -p ${env.docker_pass}"
                sh "docker push ${env.docker_user}/${params.ImageName}:latest"
                }
            }
        }

        stage('Build Container'){
            steps {
                sh "docker run -dit --name ${params.ContainerName} -p ${params.ContainerPort}:5000 prateekkumawat/${params.ImageName}:latest"
            }
        }
        
    }
    
}