pipeline {
    agent {
        label 'agent1'
    }
    tools {
        jdk 'jdk'
    }
    environment  {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git credentialsId:'git-token-pam',url:'https://github.com/mishti30/jenkins-docker-project.git',branch:'project2'
            }
        }
        stage('Sonarqube Analysis ') {
            steps {
                dir('src/neogym') {
                    withSonarQubeEnv('sonar-server') {
                        sh ''' $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=jenkins-docker-project \
                        -Dsonar.projectKey=jenkins-docker-project-neogym '''
                    }
                }
            }
        }
        stage('QualityGate') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
                }
            }
        }
        stage('OWASP Scan') {
            steps {
                dir('src/neogym') {
                    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-check'
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                }
            }
        }
        stage('TrivyFScan') {
            steps {
                dir('src/neogym') {
                    sh 'trivy fs . > trivyfs.txt'
                }
            }
        }
        stage("Image Create") {
            steps {
                script {
                    dir('src/neogym') {
                            sh 'docker build -t neogym .'
                    }
                }
            }
        }
        stage("ImagePush") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-repo-creds', usernameVariable: 'docker_user', passwordVariable: 'docker_pass')]) {
                    sh "docker tag neogym ${env.docker_user}/neogym:${BUILD_NUMBER}"
                    sh "docker login -u ${env.docker_user} -p ${env.docker_pass}"
                    sh "docker push ${env.docker_user}/neogym:${BUILD_NUMBER}"
                    }
                }
            }
        }
        stage("ImageScan") {
            steps {
                sh 'trivy image prateekkumawat/neogym:${BUILD_NUMBER} > trivyimage_${BUILD_NUMBER}.txt' 
            }
        }
        stage("ImageDepoy") { 
            steps { 
                sh 'docker run -dit --name finexo -p 8082:80  prateekkumawat/neogym:${BUILD_NUMBER}'
            }
        }
    
    }
}